name: Build

on:
  workflow_dispatch:

  push:

jobs:
  build:
    name: Build artifact
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Build
        run: |
          cd ./pwa
          npm ci
          npm run build
      - name: Test
        run: |
          cd ./pwa
          npm test
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{github.sha}}
          path: pwa/public