name: Build

jobs:
  build:
    name: Build artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Build
        run: |
          cd ./pwa
          npm ci
          npm run build